### ISSUE TITLE
this shit doesn't make me look sexy 

### ISSUE THREAD

**Issue by zzulanas** [BernardZhao/gltch#1]
0/10 I tried to put my dick in this and it didn't even glitch it

**Comment by BernardZhao** [comment]
## Holdup ✋😤
I'm redoing the entire project my own way now dw

**Comment by BernardZhao** [comment]
@zzulanas It will be done before summer ends.

**Comment by BernardZhao** [comment]
> @zzulanas It will be done before summer ends.

I lied, but how about now @zzulanas?

**Comment by BernardZhao** [comment]
Closed because no more tomfoolery on oss
